CREATE TABLE IF NOT EXISTS users (
	userId INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	firstName VARCHAR(30) NOT NULL DEFAULT '',
	lastName VARCHAR(30) NOT NULL DEFAULT '',
	email VARCHAR(50) NOT NULL DEFAULT '',
	userPassword CHAR(64),
	salt VARCHAR(64),
	date DATETIME,
	CONSTRAINT unique_email UNIQUE(email)
);

CREATE TRIGGER dateUser_created BEFORE INSERT ON users
FOR EACH ROW
SET NEW.date = NOW();