CREATE TABLE IF NOT EXISTS cities (
	cityId SMALLINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	cityName VARCHAR(30) NOT NULL DEFAULT '',
	stateFk TINYINT,
	CONSTRAINT fk_state FOREIGN KEY (stateFk) REFERENCES states (stateId) ON UPDATE CASCADE,
	CONSTRAINT unique_city UNIQUE(cityName, stateFk)
);