CREATE TABLE IF NOT EXISTS cars (
    carID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    make VARCHAR(30) NOT NULL DEFAULT 'make',
    model VARCHAR(30) NOT NULL DEFAULT 'model',
    type VARCHAR(20) NOT NULL DEFAULT 'type',
    modelYear INT NOT NULL DEFAULT 0,
    color VARCHAR(50) NOT NULL DEFAULT 'color',
    driveType VARCHAR(20) NOT NULL DEFAULT 'drive type',
    numberOfCylinders TINYINT NOT NULL DEFAULT 0,
    horsepower SMALLINT NOT NULL DEFAULT 0,
    torque SMALLINT NOT NULL DEFAULT 0,
    cityMPG SMALLINT NOT NULL DEFAULT 0,
    highwayMPG SMALLINT NOT NULL DEFAULT 0,
    combinedMPG SMALLINT NOT NULL DEFAULT 0,
    seating TINYINT NOT NULL DEFAULT 0,
    rating TINYINT NOT NULL DEFAULT 0,
    availability VARCHAR(3) NOT NULL DEFAULT ''
);