INSERT INTO models (modelName, makeFk, typeFk, year, driveTypeFk, cylinders, horsepower, torque,
	cityMpg, highwayMpg, combinedMpg, seating)
VALUES
('Civic Si', (SELECT makeId FROM makes WHERE makeName = 'Honda'),
	(SELECT typeId FROM types WHERE type = 'coupe'), 2012,
	(SELECT driveTypeId FROM drive_types WHERE driveType = 'front-wheel drive'),
	4, 201, 170, 22, 31, 25, 5),
('M5', (SELECT makeId FROM makes WHERE makeName = 'BMW'),
	(SELECT typeId FROM types WHERE type = 'sedan'), 2012,
	(SELECT driveTypeId FROM drive_types WHERE driveType = 'rear-wheel drive'),
	8, 560, 502, 14, 22, 17, 5),
('Z4', (SELECT makeId FROM makes WHERE makeName = 'BMW'),
	(SELECT typeId FROM types WHERE type = 'convertible'), 2010,
	(SELECT driveTypeId FROM drive_types WHERE driveType = 'rear-wheel drive'),
	6, 300, 300, 18, 25, 20, 2),
('Explorer', (SELECT makeId FROM makes WHERE makeName = 'Ford'),
	(SELECT typeId FROM types WHERE type = 'SUV'), 2013,
	(SELECT driveTypeId FROM drive_types WHERE driveType = 'all-wheel drive'),
	6, 290, 255, 17, 23, 19, 7),
('Fusion', (SELECT makeId FROM makes WHERE makeName = 'Ford'),
	(SELECT typeId FROM types WHERE type = 'sedan'), 2013,
	(SELECT driveTypeId FROM drive_types WHERE driveType = 'front-wheel drive'),
	4, 170, 170, 22, 34, 26, 5),
('Aventador', (SELECT makeId FROM makes WHERE makeName = 'Lamborghini'),
	(SELECT typeId FROM types WHERE type = 'supercar'), 2013,
	(SELECT driveTypeId FROM drive_types WHERE driveType = 'all-wheel drive'),
	12, 691, 508, 11, 18, 13, 2),
('Sienna', (SELECT makeId FROM makes WHERE makeName = 'Toyota'),
	(SELECT typeId FROM types WHERE type = 'minivan'), 2005,
	(SELECT driveTypeId FROM drive_types WHERE driveType = 'all-wheel drive'),
	6, 230, 242, 16, 22, 18, 7);